from model import (
  create_company
)

companies = [['Rentboy','www.rentboy.com'],
['Hustler','www.hustler.com'],
['Swingersboard','www.swingersboard.com'],
['Xtube','www.xtube.com'],
['PornHub','www.pornhub.com'],
['Brazzers','www.brazzers.com'],
['Tube8','www.tube8.com'],
['Chaturbate','www.chaturbate.com'],
['MyFreeCams','www.myfreecams.com/'],
['Nudevista','www.nudevista.com/'],
['YouPorn','www.youporn.com/'],
['Streamate','www.streamate.com'],
['Xvideos','www.xvideos.com'],
['Xhamster','www.xhamster.com'],
['XNXX','www.xnxx.com'],
['Redtube','www.redtube.com'],
['LiveJasmin','www.livejasmin.com'],
['Imagefap','www.imagefap.com/'],
['Beeg','www.beeg.com'],
['Youjizz','www.youjizz.com/'],
['Amie Street','http://amiestreet.com/page/privacy-policy'],
['Mubi','http://mubi.com/privacy_policy'],
['BabyCenter','http://www.babycenter.com/help-privacy'],
['BigTent','http://www.bigtent.com/privacy'],
['Blogger','http://www.blogger.com/privacy'],
['Bolt','http://www.bolt.com/main/authorization/privacyPolicy'],
['Cellufun','http://www.cellufun.com/about/privacy.asp'],
['Collegeblender','http://www.collegeblender.com/privacy'],
['Dailybooth','http://dailybooth.com/privacy'],
['Dailystrength','http://www.dailystrength.org/content/view/201'],
['Yahoo','http://info.yahoo.com/privacy/us/delicious/'],
['Disaboom','http://aboutus.disaboom.com/Privacy-Policy.aspx'],
['ePernicus','http://www.epernicus.com/privacy_policy'],
['Eons','http://www.eons.com/about/privacy'],
['Exploroo','http://www.exploroo.com/privacy.php'],
['FilmAffinity','http://www.filmaffinity.com/en/private.php'],
['Flickr','http://info.yahoo.com/privacy/us/yahoo/flickr/details.html'],
['FourSquare','http://foursquare.com/legal/privacy'],
['Gays.com','http://gays.com/privacyPolicy.html'],
['GogoYoko','http://www.gogoyoko.com/#/privacy'],
['Google Buzz','http://www.google.com/buzz/help/privacy.html'],
['Yammer','https://www.yammer.com/company/privacy'],
['Indaba Music','http://www.indabamusic.com/corporate/privacy'],
['iTalki','http://www.italki.com/static/privacy.htm'],
['itsmy','http://itsmy.com/umts/privacy.php'],
['Kiwibox','http://www.kiwibox.com/about/privacy'],
['Zooppa','http://zooppa.com/corporate/privacy'],
['Listography','http://www.listography.com/action/privacy'],
['Meet the Boss','http://www.meettheboss.tv/privacy/'],
['MouthShut','http://us.mouthshut.com/help/privacy.php'],
['CraveOnline','http://www.craveonline.com/privacy.php?site=www.MyAnimeList.net'],
['MyHeritage','http://www.myheritage.com/FP/Company/popup.php?p=privacy_policy'],
['MyOpera','http://my.opera.com/community/privacy/'],
['OpenDiary','http://www.opendiary.com/privacy.asp'],
['PartnerUp','http://www.partnerup.com/privacy/'],
['Present.ly','http://www.presently.com/terms#privacy'],
['quarterlife','http://www.quarterlife.com/main/authorization/privacyPolicy?previousUrl=http://www.quarterlife.com/'],
['Raptr','http://raptr.com/info/privacy'],
['Research Gate','http://www.researchgate.net/application.PrivacyPolicy.html'],
['ReverbNation.com','http://www.reverbnation.com/main/privacy'],
['Science Stage','http://sciencestage.com/resources/privacy-policy'],
['ShareTheMusic','http://www.sharethemusic.com/help/privacy'],
['SocialVibe','http://www.socialvibe.com/info#/privacy_policy/'],
['StumbleUpon','http://www.stumbleupon.com/privacy/'],
['Talkbiznow','http://www.talkbiznow.com/static/default/privacy'],
['TeachStreet','http://www.teachstreet.com/privacy-policy'],
['Tumblr','http://www.tumblr.com/privacy_policy'],
['Wee World','http://www.weeworld.com/privacy/default.aspx'],
['WeOurFamily','https://member.weourfamily.com/privacypolicy'],
['Microsoft 1','http://privacy.microsoft.com/en-us/fullnotice.mspx'],
['WiserEarth','http://www.wiserearth.org/article/Privacy'],
['Xt3','http://www.xt3.com/smallprint/privacy.php'],
['Chemistry.com','http://chemistry.com/help/privacy.aspx'],
['compatiblePartners','http://www.compatiblepartners.net/privacy/statement'],
['eHarmony','http://www.eharmony.com/privacy/statement'],
['Lavalife','http://www.lavalife.com/singles/trusted/privacy?locale=en_US&context=anrr&a=0'],
['Match.com','http://www.match.com/registration/privacystatement.aspx'],
['True.com','http://www.true.com/privacy.htm?svw=homepage'],
['Yahoo Personals','http://info.yahoo.com/privacy/us/yahoo/personals/details.html'],
['Blogger','http://www.blogger.com/privacy'],
['Ashley Madison','http://www.ashleymadison.com/app/public/privacy.p'],
['Get It On','http://getiton.com/go/page/privacy.html'],
['Friend Finder','http://friendfinder.com/go/page/privacy.html?who=r,zTsVqVEP3ewQQ2Goq9WTLDByrgSsjAOseMDeYuenBwAn61zHwCqQjUdnrn4ILZ2ffvQoDh9VKwltFViMvUsh9dV5_mpsWdG/RfZ_I6X/nrFVTB9IRb4xEEn2A6yRmF721dONO7Zex9r8O5WnEmNSSw--'],
['Matchmaker','http://matchmaker.com/SiteInformation.do?page=pp'],
['Gay.com','http://www.heremedia.com/legal/privacy_policy/'],
['Mate1','http://www.mate1.com/nw/privacy_policy'],
['Mingles','http://www.mingles.com/privacy/'],
['Wealthy Men','http://wealthymen.com/privacy.php?prg=1&id=noadvert'],
['SinglesNet','http://www.singlesnet.com/?setlocation=help&setarea=privacy&PHPSESSID=e08f738396f465f3ba1071dd5db18e68'],
['Christian Mingle','http://www.christianmingle.com/privacy.html'],
['Ge-Dating','http://dating.ge-dating.com/Privacy.aspx'],
['jDate','http://www.jdate.com/Applications/Article/ArticleView.aspx?CategoryID=1948&ArticleID=6498&HideNav=True#privacy'],
['Spark','http://www.spark.com/Applications/Article/ArticleView.aspx?CategoryID=1948&ArticleID=6498&HideNav=True#privacy'],
['Interracial Singles','http://www.interracialsingles.net/privacy.html'],
['date.com','http://date.com/SiteInformation.do?page=pp'],
['Dating Direct','http://datingdirect.com/misc/privacy_v.php'],
['Passion.com','http://passion.com/go/page/privacy.html'],
['Millionaire Mate','http://millionairemate.com/go/page/privacy.html'],
['Metrodate!','http://www.metrodate.com/privacypolicy.asp'],
['Match America','http://matchamerica.com/privacy/'],
['LoveCity','http://www.lovecity.com/privacy.htm'],
['FriendSearch','http://www.friendsearch.com/privacy.htm'],
['Planet Personals','http://planetpersonals.com/cgibin/template.cgi?template=privacypolicy'],
['DatingFaces','http://www.datingfaces.com/go/page/privacy.html'],
['MyLatinLady','http://www.mylatinlady.com/privacy.php'],
['Equestrian Singles','http://equestriansingles.com/es/security.asp'],
['Large and Lovely','http://www.largeandlovely.com/site-privacypolicy~pp-up.html'],
['gay.date.com','http://gay.date.com/SiteInformation.do'],
['Match Students','http://www.matchstudents.com/index.php?page=privacy_policy'],
['Country Singles','http://countrysingles.com/'],
['Green Singles','http://www.greensingles.com/privacy_policy.php'],
['White Women Black Men','http://whitewomenblackmen.com/privacy.php'],
['Simply Clicked','http://simplyclicked.com/privacy.htm'],
['Veggie Date','http://www.veggiedate.org/privacy.cfm'],
['Kizmeet','http://www.kizmeet.com/e/privacy_policy.htm'],
['MySpace (dynamic project)','http://www.myspace.com/index.cfm?fuseaction=misc.privacy'],
['IMDb','http://www.imdb.com/privacy'],
['CNET','http://cbsiprivacy.custhelp.com/app/answers/detail/a_id/1268/session/L2F2LzEvc2lkL19HMll4eDNr'],
['Gamespot','http://cbsiprivacy.custhelp.com/app/answers/detail/a_id/1268/session/L2F2LzEvc2lkL19HMll4eDNr'],
['IGN Boards','http://corp.ign.com/privacy.html'],
['Miniclip','http://www.miniclip.com/games/en/privacy-policy.php'],
['Slashdot','http://geek.net/privacy-statement'],
['GameFAQs','http://cbsiprivacy.custhelp.com/app/answers/detail/a_id/1268/session/L2F2LzEvc2lkL19HMll4eDNr'],
['File Front','http://www.filefront.com/privacy.php'],
['DP Review','http://www.dpreview.com/misc/privacypolicy.asp'],
['Word Reference','http://www.wordreference.com/english/Privacy%20Policy.htm'],
['Fat Wallet','http://www.fatwallet.com/privacy.php'],
['Winamp Forums','http://www.winamp.com/legal/privacy'],
['Slickdeals','http://slickdeals.net/blog/index.php/legal-privacy-policy/'],
['Newgrounds','http://www.newgrounds.com/privacy'],
['Ebaum\'s World','http://www.ebaumsworld.com/pages/privacy/'],
['Harry Potter','http://www.warnerbros.com/?page=privacy-policy/'],
['Ultimate Guitar','http://www.ultimate-guitar.com/about/privacy.htm'],
['Gamespy','http://corp.ign.com/privacy.html'],
['Zam','http://www.zam.com/privacy.html'],
['Edmunds','http://www.edmunds.com/help/about/privacy.html'],
['Playstation.com','http://us.playstation.com/support/privacypolicy/index.htm'],
['Ars Technica','http://arstechnica.com/site/privacy-policy.ars'],
['NamePros','http://www.namepros.com/privacypolicy.php'],
['SomethingAwful','http://www.somethingawful.com/d/feature-articles/website-privacy-policy.php'],
['Bodybuilding','http://www.bodybuilding.com/fun/disclaim.htm#privacy'],
['Soompi','http://www.soompi.com/privacy'],
['India Forums','http://www.india-forums.com/privacy_policy.asp'],
['Artix Entertainment','http://www.aq.com/aw-privacy.asp'],
['vBulletin.com','http://www.vbulletin.com/privacy.php'],
['DSL Reports','http://www.dslreports.com/privacy'],
['GameTrailers','http://www.gametrailers.com/privacy.php'],
['Airliners.net','http://www.airliners.net/privacypolicy/'],
['AMD Forums','http://www.amd.com/us/aboutamd/Pages/privacy.aspx'],
['MozillaZine','http://www.mozillazine.org/privacypolicy.html'],
['SimpleMachines (dynamic)','http://www.simplemachines.org/about/privacy.php'],
['Pure Volume','http://www.purevolume.com/privacy_policy'],
['Hardwarezone','http://www.hardwarezone.com/pages/privacy'],
['Wizards Play Network','http://www.wizards.com/Company/About.aspx?'],
['WebMediaBrands','http://www.webmediabrands.com/corporate/privacy/aup.html'],
['Money Saving Expert','http://www.moneysavingexpert.com/site/privacy-policy'],
['Two Plus Two','http://www.twoplustwo.com/privacy.php'],
['Lonely Planet','http://www.lonelyplanet.com/legal/privacy-policy'],
['Sound Click','http://www.soundclick.com/docs/legal.cfm?site=privacy'],
['Mac Rumors','http://www.macrumors.com/privacy.shtml'],
['AfterDawn','http://www.afterdawn.com/general/legal.cfm'],
['Teamxbox','http://corp.ign.com/privacy.html'],
['Steam','http://www.valvesoftware.com/privacy.html'],
['Television without Pity','http://www.televisionwithoutpity.com/privacy.php'],
['Video Help','http://www.videohelp.com/contact#privacy'],
['Ubi.com','http://www.ubi.com/US/Info/Info.aspx?tagname=PrivacyPolicy'],
['Sign On San Diego','http://www.signonsandiego.com/privacy/'],
['Microsoft 2','http://privacy.microsoft.com/en-us/fullnotice.mspx'],
['Adult Friend Finder','http://adultfriendfinder.com/go/page/privacy.html'],
['A Small World','http://www.asmallworld.net/publicpages/privacy.php'],
['Asu Is Talking','http://www.asuistalking.com/privacy'],
['Biip','http://www.biip.no/default.aspx?section=articles&name=privacy'],
['Bebo','http://www.bebo.com/Privacy2.jsp'],
['Bahu','http://www.bahu.com/privacy'],
['Badoo','http://badoo.com/privacy'],
['Athlinks','http://www.athlinks.com/helpPrivacy.aspx'],
['Avatars United','http://www.avatarsunited.com/en/info/privacy_policy'],
['Boomj','http://www.boomj.com/privacy'],
['Experience Project','http://www.experienceproject.com/privacy.php'],
['Don\'t Stay In','http://www.dontstayin.com/pages/legalinformationpolicy'],
['DeviantArt','http://about.deviantart.com/policy/privacy/'],
['Couch Surfing','http://www.couchsurfing.com/privacy.html'],
['Classmates','http://www.classmates.com/cmo/privacy.jsp'],
['Care2','http://www.care2.com/help/general/privacy.html'],
['Cake Financial','https://www.cakefinancial.com/about/privacy-policy'],
['Broadcaster','http://www.broadcaster.com/privacy'],
['CafeMom','http://www.cafemom.com/about/privacy_policy.php'],
['BuzzNet','http://www.buzznet.com/www/privacy/'],
['Facebook','http://www.facebook.com/policy.php'],
['Faceparty','http://www.faceparty.com/static/privacy.aspx'],
['hi5','http://www.hi5.com/friend/displayPrivacy.do'],
['iMeem','http://www.imeem.com/legal/privacy.aspx'],
['Hyves','http://www.hyves.nl/privacy/'],
['Hyves','http://www.hyves.nl/useragreement/'],
['Horseland','http://www.horseland.com/terms.asp#privacystatement'],
['Habbo','http://www.habbo.com/help/61'],
['GamerDNA','http://www.gamerdna.com/PrivacyPolicy.html'],
['GoodReads','http://www.goodreads.com/about/privacy'],
['Geni','http://www.geni.com/company/privacy_policy'],
['Gather','http://www.gather.com/privacy.jsp'],
['Gaia Online','http://www.gaiaonline.com/info/index.php?mode=privacy'],
['Fubar','http://www.fubar.com/privacy.php'],
['Friendster','http://www.friendster.com/info/privacy.php'],
['Fotolog','http://info.fotolog.com/privacy'],
['Flixster','http://www.flixster.com/misc/privacy'],
['Makeshift Online','http://www.makeshiftonline.net/privacy.php'],
['Google Orkut','http://www.orkut.com/html/en-US/privacy.orkut.html'],
['OK Cupid','http://www.okcupid.com/privacy/'],
['Ohloh','http://www.ohloh.net/about/privacy'],
['Ning','http://about.ning.com/privacy.php'],
['Nexopia','http://www.nexopia.com/privacy.php'],
['Netlog','http://en.netlog.com/go/about/legal/view=privacy'],
['MyYearBook','http://www.myyearbook.com/privacy.php'],
['MySpace','http://www.myspace.com/index.cfm?fuseaction=misc.privacy'],
['MyChurch','http://www.mychurch.org/info/privacy.php'],
['Muxlim','http://muxlim.com/privacy/'],
['Multiply','http://multiply.com/info/privacy'],
['Mog','http://mog.com/privacy'],
['Mocospace','http://www.mocospace.com/html/privacy.jsp'],
['Migente','http://www.migente.com/misc/tos.html#privacy'],
['Meetup','http://www.meetup.com/privacy/'],
['LiveMocha','http://www.livemocha.com/pages/privacy'],
['LiveJournal','http://www.livejournal.com/legal/privacy.bml'],
['LinkedIn','http://www.linkedin.com/static?key=privacy_policy&trk=hb_ft_priv'],
['LifeKnot','http://www.lifeknot.com/legal/privacy.php'],
['LibraryThing','http://www.librarything.com/privacy'],
['Last.fm','http://www.last.fm/legal/privacy'],
['JammerDirect','http://www.jammerdirect.com/Home/tabid/91/ctl/Privacy/Default.aspx'],
['Jaiku','http://jaiku.com/privacy'],
['Plaxo','http://www.plaxo.com/about/privacy_policy'],
['Playboy','http://www.playboyu.com/pbu_public/index.php?act=privacy'],
['Plurk','http://www.plurk.com/privacy'],
['Passport Stamp','http://www.passportstamp.com/privacy_policy'],
['Raverly','http://www.ravelry.com/about/privacy'],
['Reunion','http://www.reunion.com/PrivacyPolicy.pub'],
['Shelfari','http://www.shelfari.com/Privacy.aspx'],
['Sonico','http://www.sonico.com/privacy-general.php'],
['Stickam','http://www.stickam.com/about/privacy.do'],
['The Student Center Network','http://www.student.com/privacy.php'],
['Taltopia','http://www.taltopia.com/privacy_popup.aspx'],
['Twitter','http://twitter.com/privacy'],
['Tribe','http://www.tribe.net/template/pub%2CPrivacy.vm'],
['OutEverywhere','http://www.outeverywhere.com/gay/privacy.cgi'],
['Faces','http://www.faces.com/privacy'],
['Vampirefreaks','http://vampirefreaks.com/privacy.php'],
['SixApart','http://www.sixapart.com/vox/us/pp/'],
['Wasabi','http://uk.wasabi.com/Privacy.aspx'],
['Wayn','http://www.wayn.com/privacy.html'],
['Microsoft 3','http://privacy.microsoft.com/en-us/fullnotice.mspx'],
['wis.dm','http://wis.dm/corp/privacy'],
['Xanga','http://help.xanga.com/about/privacypolicy.htm'],
['Xing','http://www.xing.com/app/user?op=tandc;what=dp'],
['Yelp','http://www.yelp.com/static?p=privacy'],
['Dropbox','http://www.dropbox.com/dmca#privacy'],
['Amazon','http://www.amazon.com/privacy'],
['SugarSync','http://www.sugarsync.com/privacy.html'],
['Google','http://music.google.com/about/privacy.html'],
['Pandora','http://www.pandora.com/privacy/'],
['Twilio','http://www.twilio.com/legal/privacy'],
['Google','http://www.google.com/privacy/privacy-policy.html'],
['Google','http://www.google.com/apps/intl/en/terms/user_privacy.html'],
['Google','http://www.google.com/privacy/privacy-policy.html'],
['Google','http://www.google.com/apps/intl/en/terms/user_privacy.html'],
['Grooveshark','http://www.grooveshark.com/privacy'],
['Spideroak','https://spideroak.com/privacy_policy'],
['Ubuntu','https://one.ubuntu.com/privacy/'],
['Wuala','http://www.wuala.com/en/about/privacy'],
['Syncplicity','http://www.syncplicity.com/legal/privacy-policy.html'],
['GetCloudapp','http://support.getcloudapp.com/customer/portal/articles/208761-privacy-policy'],
['Zumodrive','https://www.zumodrive.com/privacy'],
['Google','http://www.google.com/privacy/privacy-policy.html'],
['Rollbase','http://www.rollbase.com/privacy.shtml'],
['Caspio','http://www.caspio.com/company/legal/privacy-statement.aspx'],
['Squarespace','http://www.squarespace.com/privacy/'],
['Salesforce','http://www.salesforce.com/company/privacy/full_privacy.jsp'],
['Google','http://www.google.com/intl/en-US/+/policy/+1button.html'],
['Reddit','http://www.reddit.com/help/privacypolicy'],
['Google','http://www.google.com/intl/en/mobile/privacy.html'],
['Google','http://www.google.com/intl/en/policies/privacy/'],
['Google','http://www.google.com/chrome/intl/en/privacy.html'],
['Google','http://books.google.com/intl/en/googlebooks/privacy.html'],
['google','http://wallet.google.com/files/privacy.html?hl=en'],
['Pinterest','http://pinterest.com/about/privacy/'],
['23andMe','https://www.23andme.com/'],
['Abbott','http://www.abbott.com/privacy-policy.html'],
['Alere','https://www.alere.com/en/home/privacy.html'],
['Amazon UK','https://www.amazon.co.uk/gp/help/customer/display.html/ref=footer_privacy?ie=UTF8&nodeId=201909010'],
['Ambry Genetics','https://www.ambrygen.com/legal/privacy-policy'],
['Ancestry DNA','https://www.ancestry.com/cs/privacyphilosophy'],
['Assurex Health','https://assurexhealth.com/privacy/'],
['AstraZeneca','https://www.globalprivacy.astrazeneca.com/'],
['Athletigen','https://athletigen.com'],
['BGI Genomics Co. Ltd.','https://www.bgi.com/us/resources/confidentiality-policy/'],
['CDC','https://www.cdc.gov/Other/privacy.html'],
['Enpnetwork','https://www.enpnetwork.com/legal/privacy-policy'],
['Centogene','https://www.centogene.com/data-protection.html'],
['Cepheid','http://www.cepheid.com/us/privacy'],
['CombiMatrix','https://combimatrix.com/privacy-policy'],
['Complete Genomics - BGI','http://www.completegenomics.com/privacy/'],
['Cordlife','https://www.cordlife.com/sg/privacy-policy'],
['Dna Diagnostics Center','https://dnacenter.com/about-ddc/privacy-policy/'],
['Danaher','http://www.danaher.com/data-privacy-policy'],
['Dante Labs','https://us.dantelabs.com/pages/privacy-policy'],
['Edico Genome','http://edicogenome.com/privacy-policy/'],
['Fabric Genomics','https://www.fabricgenomics.com/privacy-policy/'],
['Floragenex','https://www.iubenda.com/privacy-policy/51305019/legal?ifr=true&height=512'],
['GE Global Research','https://www.ge.com/privacy'],
['GHO Capital','http://ghocapital.com/privacy-terms/'],
['Gene by Gene Ltd','https://www.genebygene.com/assets/gbg/privacy/GenebyGene_EUPS_Swiss_PP_6_12_18-12c82a1ece2c61e78eae614b7eda52b8.pdf'],
['GeneInsight','https://www.partners.org/Notices/default.aspx'],
['Genesis Genetics','https://www.coopergenomics.com/data-privacy-policy/'],
['Genome.One','https://www.genome.one/privacy-policy'],
['Genomic Health','http://www.genomichealth.com/en-US/privacy_policies'],
['Genomics Personalized Health','https://genomicspersonalizedhealth.com/privacy-policy'],
['Genoptix Lab','https://genoptix.com/legal/'],
['Grail','https://grail.com/privacy/'],
['Helix','https://www.helix.com/privacy'],
['Human Longevity, Inc.','https://www.humanlongevity.com/privacy-policy/'],
['IBM Watson','https://www.ibm.com/privacy/us/en/?lnk=flg-priv-usen'],
['Illumina','https://www.illumina.com/company/legal/corporate-privacy-policy.html'],
['Invitae','https://www.invitae.com/en/privacy/'],
['Konica Minolta','konica.minolta.com'],
['MDxHealth','https://mdxhealth.com/privacy-policy'],
['Myriad Genetics','https://myriad.com/privacy-policy/'],
['NeoGenomics','https://neogenomics.com/company/regulatory-and-licensing/website-privacy-policy'],
['Novartis','https://www.novartis.com/privacy-policy#ui-id-1=0'],
['ORIG3N','https://orig3n.com/privacy-policy/'],
['OneOme','https://oneome.com/privacy'],
['Oxford Nanopore Technologies','https://nanoporetech.com/privacy-policy'],
['Pacific Biosciences','https://www.pacb.com/legal-and-trademarks/privacy-policy/'],
['PerkinElmer','http://www.perkinelmer.com/corporate/policies/'],
['Phospohorus','https://phosphorus.com/notice-of-privacy-practices/'],
['PlumCare','https://www.plumcarehealth.com/guest/privacy-policy'],
['Qiagen','https://www.qiagen.com/us/trademarks-and-disclaimers/privacy-policy/?akamai-feo=off'],
['Rady Children\'s','https://www.rchsd.org/privacy/'],
['Roche Molecular Diagnostics','https://molecular.roche.com/privacy-policy/'],
['Sedia Biosciences','http://www.sediabio.com/privacy'],
['Sequencing.com','https://sequencing.com/privacy-policy'],
['Siemens Healthcare','https://usa.healthcare.siemens.com/siemens-website-privacy-policy'],
['Sunquest','https://www.sunquestinfo.com/privacy-policy/'],
['The Cooper Companies\'','https://www.coopergenomics.com/data-privacy-policy/'],
['Thermo Fisher','https://www.thermofisher.com/us/en/home/global/privacy-policy.html'],
['Toolbox Genomics','https://www.toolboxgenomics.com/privacy-policy/'],
['Veritas Genetics','https://www.veritasgenetics.com/sites/default/files/media/documents/Privacy_Statement_v0.3_05.25.18.pdf'],
['WGS','http://www.nygenome.org/site-terms-conditions/'],
['miRagen Therapeutics','http://www.miragen.com/privacy-policy/']]

if __name__ == "__main__":
  for name, url in companies:
    create_company(name, url, {})

